#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.11
# In conjunction with Tcl version 8.6
#    Mar 20, 2018 02:56:36 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import football_monitor_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Football_Monitor (root)
    football_monitor_support.init(root, top)
    root.mainloop()
    top.lblHomeTeam.configure(text="Anyad")

w = None
def create_Football_Monitor(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    #global w, w_win, rt
    #rt = root
    #w = Toplevel (root)
    top = Football_Monitor (root)
    football_monitor_support.init(w, top, *args, **kwargs)
    return (w,top)

def destroy_Football_Monitor():
    global w
    w.destroy()
    w = None


class Football_Monitor:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        font10 = "-family {Segoe UI} -size 16 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font11 = "-family {Segoe UI} -size 12 -weight normal -slant "  \
            "roman -underline 1 -overstrike 0"
        font12 = "-family {Segoe UI} -size 20 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 14 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("405x152+601+276")
        top.title("Football Monitor")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.lblTime = Label(top)
        self.lblTime.place(relx=0.43, rely=0.33, height=31, width=45)
        self.lblTime.configure(activebackground="#f9f9f9")
        self.lblTime.configure(activeforeground="black")
        self.lblTime.configure(background="#d9d9d9")
        self.lblTime.configure(disabledforeground="#a3a3a3")
        self.lblTime.configure(font=font9)
        self.lblTime.configure(foreground="#000000")
        self.lblTime.configure(highlightbackground="#d9d9d9")
        self.lblTime.configure(highlightcolor="black")
        self.lblTime.configure(text='''0:00''')

        self.lblHomeScore = Label(top)
        self.lblHomeScore.place(relx=0.4, rely=0.53, height=33, width=22)
        self.lblHomeScore.configure(activebackground="#f9f9f9")
        self.lblHomeScore.configure(activeforeground="black")
        self.lblHomeScore.configure(background="#d9d9d9")
        self.lblHomeScore.configure(disabledforeground="#a3a3a3")
        self.lblHomeScore.configure(font=font12)
        self.lblHomeScore.configure(foreground="#000000")
        self.lblHomeScore.configure(highlightbackground="#d9d9d9")
        self.lblHomeScore.configure(highlightcolor="black")
        self.lblHomeScore.configure(text='''0''')

        self.lblOpponentScore = Label(top)
        self.lblOpponentScore.place(relx=0.52, rely=0.53, height=33, width=22)
        self.lblOpponentScore.configure(activebackground="#f9f9f9")
        self.lblOpponentScore.configure(activeforeground="black")
        self.lblOpponentScore.configure(background="#d9d9d9")
        self.lblOpponentScore.configure(disabledforeground="#a3a3a3")
        self.lblOpponentScore.configure(font=font12)
        self.lblOpponentScore.configure(foreground="#000000")
        self.lblOpponentScore.configure(highlightbackground="#d9d9d9")
        self.lblOpponentScore.configure(highlightcolor="black")
        self.lblOpponentScore.configure(text='''0''')

        self.lblHomeTeam = Label(top)
        self.lblHomeTeam.place(relx=0.02, rely=0.53, height=36, width=125)
        self.lblHomeTeam.configure(activebackground="#f9f9f9")
        self.lblHomeTeam.configure(activeforeground="black")
        self.lblHomeTeam.configure(background="#d9d9d9")
        self.lblHomeTeam.configure(disabledforeground="#a3a3a3")
        self.lblHomeTeam.configure(font=font10)
        self.lblHomeTeam.configure(foreground="#000000")
        self.lblHomeTeam.configure(highlightbackground="#d9d9d9")
        self.lblHomeTeam.configure(highlightcolor="black")
        self.lblHomeTeam.configure(text='''None''')

        self.lblOpponentTeam = Label(top)
        self.lblOpponentTeam.place(relx=0.64, rely=0.53, height=31, width=126)
        self.lblOpponentTeam.configure(activebackground="#f9f9f9")
        self.lblOpponentTeam.configure(activeforeground="black")
        self.lblOpponentTeam.configure(background="#d9d9d9")
        self.lblOpponentTeam.configure(disabledforeground="#a3a3a3")
        self.lblOpponentTeam.configure(font=font10)
        self.lblOpponentTeam.configure(foreground="#000000")
        self.lblOpponentTeam.configure(highlightbackground="#d9d9d9")
        self.lblOpponentTeam.configure(highlightcolor="black")
        self.lblOpponentTeam.configure(text='''None''')

        self.lblHyphenText = Label(top)
        self.lblHyphenText.place(relx=0.46, rely=0.53, height=33, width=22)
        self.lblHyphenText.configure(activebackground="#f9f9f9")
        self.lblHyphenText.configure(activeforeground="black")
        self.lblHyphenText.configure(background="#d9d9d9")
        self.lblHyphenText.configure(disabledforeground="#a3a3a3")
        self.lblHyphenText.configure(font=font12)
        self.lblHyphenText.configure(foreground="#000000")
        self.lblHyphenText.configure(highlightbackground="#d9d9d9")
        self.lblHyphenText.configure(highlightcolor="black")
        self.lblHyphenText.configure(text='''-''')

        self.lblHomeTeamText = Label(top)
        self.lblHomeTeamText.place(relx=0.11, rely=0.26, height=27, width=48)
        self.lblHomeTeamText.configure(activebackground="#f9f9f9")
        self.lblHomeTeamText.configure(activeforeground="black")
        self.lblHomeTeamText.configure(background="#d9d9d9")
        self.lblHomeTeamText.configure(disabledforeground="#a3a3a3")
        self.lblHomeTeamText.configure(font=font11)
        self.lblHomeTeamText.configure(foreground="#000000")
        self.lblHomeTeamText.configure(highlightbackground="#d9d9d9")
        self.lblHomeTeamText.configure(highlightcolor="black")
        self.lblHomeTeamText.configure(text='''Home''')

        self.lblOpponentTeamText = Label(top)
        self.lblOpponentTeamText.place(relx=0.7, rely=0.26, height=27, width=76)
        self.lblOpponentTeamText.configure(activebackground="#f9f9f9")
        self.lblOpponentTeamText.configure(activeforeground="black")
        self.lblOpponentTeamText.configure(background="#d9d9d9")
        self.lblOpponentTeamText.configure(disabledforeground="#a3a3a3")
        self.lblOpponentTeamText.configure(font=font11)
        self.lblOpponentTeamText.configure(foreground="#000000")
        self.lblOpponentTeamText.configure(highlightbackground="#d9d9d9")
        self.lblOpponentTeamText.configure(highlightcolor="black")
        self.lblOpponentTeamText.configure(text='''Opponent''')



